package com.java.oop;

public class Assignment7 {
    // CREATE A BASE ABSTRACT CLASS CALLED AS CONTROLUNIT
    // CREATE CONCRETE METHOD LIKE calculateRpm(int accelerateInput)
    // CREATE ABSTRACT METHOD LIKE tuneGear(int speed)
    // CREATE A CHILD CLASS CALLED AS CAR WHICH EXTENDS CONTROLUNIT
    // IMPLEMENT tuneGear method in CAR
    // INSTANTIATE A CAR AND EXECUTE calculateRpm and tuneGear.. methods

    // CREATE A PHONE CLASS
    // CREATE A SIMCARD INTERFACE
    // WRITE SOME STANDARD METHOD SIGNATURES IN SIMCARD INTERFACE
    // IMPLEMENT SIMCARD INTERFACE IN PHONE CLASS
    // CREATE DIFFERENT PHONES WHICH CAN USE A SIMCARD
}
