package com.java.oop;

public class Assignment5 {
    // CREATE A PARENT CLASS CALLED AS VEHICLE
    // DECLARE PROPERTIES OF A VEHICLE
    // DECLARE METHODS LIKE START VEHICLE, STOP VEHICLE
    // CREATE A CLASS CALLED AS BOAT
    // ASSIGN BOAT SPECIFIC PROPERTIES (APART FROM VEHICLE)
    // DECLARE A METHOD CALLED AS moveBoat(int speed)
    // BOAT SHOULD ONLY MOVE IF VEHICLE IS STARTED!
    // CREATE A CLASS CALLED AS TRUCK
    // ASSIGN TRUCK SPECIFIC PROPERTIES
    // DECLARE METHOD CALLED moveTruck(int speed)
    // CHECK THAT MOVE TRUCK SHOULD WORK ONLY IF VEHICLE IS STARTED!
    // CHECK THAT APPROPRIATE GEAR IS SELECTED WHEN A SPEED IS SUPPLIED TO TRUCK
}
