package com.java.oop.collections;

public class Assignment10 {
    // PRACTICE LIST AND SET INTERFACE EXAMPLES
    // CREATE A CLASS CALLED AS ShoppingCart
    // CREATE METHODS TO ADD AND REMOVE PRODUCTS
    // DECLARE ANOTHER CLASS CALLED AS FLIPKART
    // CREATE LIST OF SHOPPING CART
    // PROVIDE A DYNAMIC MENU TO ADD AND REMOVE ITEMS TO AND FROM CART
    // SHOW TOTAL AMOUNT FOR ITEMS IN YOUR CART
}
