package com.java.oop.composition;

public class Assignment9 {
    // MODEL A PHONE BY COMPOSING ONE OBJECT AS MEMBER OF OTHER OBJECT
    // CREATE A CLASS CALLED AS PHONE
    // PHONE "HAS-A" DISPLAY
    // CREATE A CLASS CALLED AS DISPLAY
    // PHONE "HAS-A" OS
    // CREATE A CLASS CALLED AS OS
    // PHONE "HAS-A" SIMCARD
    // CREATE A CLASS CALLED AS SIMCARD
    // ASSIGN MEMBER VARIABLES TO PHONE, DISPLAY, OS and SIMCARD
    // PRINT THE PHONE SPECS as STRING.
}
